version: '3.7'
services:
  devbox:
    container_name: devbox
    build:
      context: ./
      dockerfile: docker/DevBox.DockerFile
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    ports:
      - "80:80"
    volumes:
            - ./project:/var/www/html:z
    working_dir: /var/www/html
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    build:
      context: ./
      dockerfile: docker/MariaDB.DockerFile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
            - ./docker/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
            - ./docker/mysql:/var/lib/mysql
